---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/shops/{id}":
    get:
      summary: Retrieves a shop
      tags:
      - Shops
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: name found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              address:
                type: string
              city:
                type: string
              country:
                type: string
              zip_code:
                type: string
            required:
            - id
            - name
            - address
            - city
            - country
            - zip_code
        '404':
          description: shop not found
